server:
  port: 80
spring:
  application:
    name: Spring_Resume_Project
  devtools:
    livereload:
      enabled: true #화면 갱신
    restart:
      enabled: true #재시작
  thymeleaf:
    cache: false #캐쉬 없음

  security:
    user:
      name: test
      password: 1234

  #mysql설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_resume
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB #파일 1개당 20mb가 최대가 되도록 설정
      max-request-size: 100MB #총 파일에 100mb까지만 업로드 되도록 설정

  resumeFileLocation: C:/resumeProject/resumeFile
  uploadPath: file///C:/resumeProject


logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace